---
title: 'Simple Linear Regression & Diagnostics'
author: "Mariam Walaa"
output:
  html_document: default
  pdf_document: default
---

```{r warning = FALSE, message = FALSE}
library(tidyverse)
library(magrittr)
library(car)
library(alr3)
library(corrplot)
```

### Data

This data set comes from the UCI Machine Learning Repository and can be found
[here](https://archive.ics.uci.edu/ml/datasets/Facebook+metrics). According to the data
abstract, this data set consists of posts published during the year of 2014 on the
Facebook pages of a renowned cosmetics brand. The data set contains 500 rows and 19
variables about each post.

```{r}
facebook <- read.csv(file = '../data/Facebook_metrics/dataset_Facebook.csv', sep = ';')
```

```{r echo = FALSE}
colnames(facebook) <- c("total_page_likes", "type", "category", "month_posted", "weekday_posted", "hour_posted",
                        "paid", "total_reach", "total_impressions", "engaged_users",  "consumers", "consumptions",
                        "impressions_by_page_likers", "reach_by_page_likers", "engagements_by_page_likers", 
                        "comments", "likes", "shares", "total_interactions")
```

```{r, fig.width = 20, fig.height = 20}
plot(facebook)
```

```{r}
X <- facebook$consumers
hist(X, breaks = 200)
shapiro.test(bcPower(X, powerTransform(X)$lambda))
facebook$X_trans <- bcPower(X, powerTransform(X)$lambda)
hist(facebook$X_trans, breaks = 30)
```

```{r}
Y <- facebook$engaged_users
hist(Y, breaks = 200)
shapiro.test(bcPower(Y, powerTransform(Y)$lambda))
facebook$Y_trans <- bcPower(Y, powerTransform(Y)$lambda)
hist(facebook$Y_trans, breaks = 30)
```

```{r, fig.width = 10, fig.height = 6}
plot(X, Y)
abline(lsfit(X, Y))
summary(lm(Y ~ X))
shapiro.test(lm(Y_trans ~ X_trans, data = facebook)$residuals)
```

```{r, fig.width = 12, fig.height = 8}
par(mfrow = c(2,2))
plot(lm(Y ~ X))
```

```{r, fig.width = 10, fig.height = 6}
plot(facebook$X_trans, facebook$Y_trans)
abline(lsfit(facebook$X_trans, facebook$Y_trans))
summary(lm(Y_trans ~ X_trans, data = facebook))
shapiro.test(lm(Y_trans ~ X_trans, data = facebook)$residuals)
```

```{r, fig.width = 12, fig.height = 8}
par(mfrow = c(2,2))
plot(lm(Y_trans ~ X_trans, data = facebook))
```

```{r}
model <- lm(Y_trans ~ X_trans, data = facebook)
```

```{r}
anova(model, update(model, ~.-X_trans)) 
```

<!-- Which variables are most correlated? -->
<!-- Are they normally distributed? -->
<!-- Does it look like we can apply a linear regression to it? -->
<!-- Is the independent variable statistically significant? -->
<!-- Is the model statistically significant? -->
<!-- Is this model better than an intercept-only model? -->